# Chapter 3 - Manipulating Tabular Data Using Pandas

- [What is Pandas](#what-is-pandas)
- [Pandas Series](#pandas-series)
  - [Creating a Series Using a Specified Index](#creating-series)
  - [Accesing Elements in a Series](#accesing-elements-series)
  - [Specifying a Datetime Range as the Index of a Series](#datetime-index)
  - [Date Ranges](#date-ranges)
- [Pandas DataFrame](#pandas-dataframe)
  - [Creating a DataFrame](#creating-dataframe)
  - [Specifying the Index in a DataFrame](#dataframe-index)
  - [Generating Descriptive Statistics on the DataFrame](#dataframe-statistics)
  - [Extracting from DataFrames](#dataframe-extracting)
  - [Selecting a Single Cell in a DataFrame](#single-cell-dataframe)
  - [Selecting Based on Cell Value](#selecting-based-cell-value)
  - [Transforming DataFrames](#transforming-dataframes)
  - [Checking to See If a Result Is a DataFrame or Series](#dataframe-series)
  - [Sorting Data in a DataFrame](#sorting-dataframe)
  - [Applying Functions to a DataFrame](#functions-dataframe)
  - [Adding and Removing Rows and Columns in a DataFrame](#rows-columns)
  - [Generating a Crosstab](#crosstab)

<a id="#what-is-pandas"></a>
## What is Pandas?
Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive.<br> **Pandas stands for Panel Data Analysis.**


<a id="pandas-series"></a>
## Pandas Series

A Pandas Series is a one-dimensional NumPy-like array, with each element having an index (0, 1, 2, . . . by default); a Series behaves very much like a dictionary that includes an index.<br>
To create a Series, you first need to import the pandas library (the convention is to use pd as the alias) and then use the Series class:

In [1]:
import pandas as pd
series_uno = pd.Series([1,2,3,4,5])
print(series_uno)

0    1
1    2
2    3
3    4
4    5
dtype: int64


By default, the index of a Series starts from 0

<a id="creating-series"></a>
### Creating a Series Using a Specified Index
You can specify an optional index for a Series using the index parameter:

In [2]:
series_dos = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series_dos)

a    1
b    2
c    3
d    4
c    5
dtype: int64


It is worth noting that the index of a Series need not be unique.

<a id="accesing-elements-series"></a>
### Accesing Elements in a Series
Accessing an element in a Series is similar to accessing an element in an array. 

In [3]:
print(series_uno[2])

3


The iloc indexer allows you to specify an element via its position.

In [4]:
#  based on the position of the index
print(series_uno.iloc[2]) 

3


Alternatively, you can also specify the value of the index of the element you wish to access 

In [5]:
print(series_dos['d'])

4


The loc indexer allows you to specify the label (value) of an index

In [6]:
# based on the label in the index
print(series_dos.loc['d'])

4


In [7]:
# more than 1 row has the index 'c'
print(series_dos['c'])

c    3
c    5
dtype: int64


You can also perform slicing on a Series:

In [8]:
print(series_dos[2:])

c    3
d    4
c    5
dtype: int64


In [9]:
print(series_dos.iloc[2:])

c    3
d    4
c    5
dtype: int64


<a id="datetime-index"></a>
### Specifying a Datetime Range as the Index of a Series

Often, you want to create a timeseries, such as a running sequence of dates in a month. You could use the `date _ range()` function for this purpose:

In [10]:
dates1 = pd.date_range('20190525', periods=12)
print(dates1)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[ns]', freq='D')


To assign the range of dates as the index of a Series, use the index property 

In [11]:
series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
series.index = dates1
print(series)

2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64


<a id="date-ranges"></a>
### Date Ranges

The periods parameter specifies how many dates you want to create, and the default frequency is `D` (for Daily). If you want to change the frequency to month, use the `freq` parameter and set it to `M`

In [12]:
dates2 = pd.date_range('2019-05-01', periods=12, freq='M')
print(dates2)

DatetimeIndex(['2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31',
               '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30'],
              dtype='datetime64[ns]', freq='M')


Notice that when the frequency is set to month, the day of each date will be the last day of the month. If you want the date to start with the first day of the month, set the `freq` parameter to `MS`

In [13]:
dates2 = pd.date_range('2019-05-01', periods=12, freq='MS')
print(dates2)

DatetimeIndex(['2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01',
               '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01',
               '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01'],
              dtype='datetime64[ns]', freq='MS')


**TIP** For other date frequencies, check out the Offset Aliases section of the documentation [here](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)

In addition to setting dates, you can also set the time:

In [14]:
date3 = pd.date_range('2019/05/17 09:00:00', periods=8, freq='H')
print(date3)

DatetimeIndex(['2019-05-17 09:00:00', '2019-05-17 10:00:00',
               '2019-05-17 11:00:00', '2019-05-17 12:00:00',
               '2019-05-17 13:00:00', '2019-05-17 14:00:00',
               '2019-05-17 15:00:00', '2019-05-17 16:00:00'],
              dtype='datetime64[ns]', freq='H')


<a id="pandas-dataframe"></a>
## Pandas DataFrame

A Pandas DataFrame is a two-dimensional NumPy-like array. You can think of
it as a table.<br>
A DataFrame is very useful in the world of data science and machine learning, as it closely mirrors how data are stored in real-life. Imagine the data stored in a spreadsheet, and you would have a very good visual impression of a DataFrame.

<a id="creating-dataframe"></a>
### Creating a DataFrame
You can create a Pandas DataFrame using the DataFrame() class:

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10,4), columns=list('ABCD'))
print(df)

          A         B         C         D
0  0.118884  0.385206 -0.320386 -0.456324
1  0.734527 -1.737722 -0.164112  0.741052
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590
4 -0.567627 -0.572061  1.427365  0.451036
5 -0.572796 -0.820218 -0.156499 -0.070004
6  1.899104 -0.192962 -0.676094  0.102150
7 -1.950551  0.359557  1.034092 -0.608499
8 -0.082232 -0.704745  2.212451 -0.796912
9 -0.277762  0.410761  0.233124 -2.040270


In [16]:
df.to_csv(r'C:\Users\srr2602\Desktop\Test\Python\machine-learning-with-python\data.csv', index = None, header=True)

<a id="dataframe-index"></a>
### Specifying the Index in a DataFrame

In [17]:
df_2 = pd.read_csv('data.csv')
days = pd.date_range('20190525', periods=10)
df_2.index = days
print(df_2)

                   A         B         C         D
2019-05-25  0.118884  0.385206 -0.320386 -0.456324
2019-05-26  0.734527 -1.737722 -0.164112  0.741052
2019-05-27 -1.024309  0.056186  2.075116 -0.288879
2019-05-28 -1.263449 -0.123481 -0.549220 -0.444590
2019-05-29 -0.567627 -0.572061  1.427365  0.451036
2019-05-30 -0.572796 -0.820218 -0.156499 -0.070004
2019-05-31  1.899104 -0.192962 -0.676094  0.102150
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-06-02 -0.082232 -0.704745  2.212451 -0.796912
2019-06-03 -0.277762  0.410761  0.233124 -2.040270


To get the index of the DataFrame, use the index property as follows:

In [18]:
print(df_2.index)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03'],
              dtype='datetime64[ns]', freq='D')


If you want to get the values of the entire DataFrame as a two-dimensional
ndarray, use the values property:

In [19]:
print(df_2.values)

[[ 0.11888394  0.38520586 -0.32038616 -0.45632357]
 [ 0.734527   -1.73772243 -0.16411162  0.74105206]
 [-1.02430875  0.05618593  2.07511605 -0.28887874]
 [-1.26344935 -0.12348073 -0.54921992 -0.44459039]
 [-0.567627   -0.57206068  1.42736479  0.45103603]
 [-0.57279634 -0.8202182  -0.15649908 -0.07000413]
 [ 1.89910352 -0.19296232 -0.67609395  0.10215024]
 [-1.95055105  0.35955661  1.03409192 -0.60849859]
 [-0.08223218 -0.70474496  2.21245131 -0.79691157]
 [-0.27776176  0.41076073  0.23312379 -2.04027006]]


<a id="dataframe-statistics"></a>
### Generating Descriptive Statistics on the DataFrame
The Pandas DataFrame comes with a few useful functions to provide you with some detailed statistics about the values in the DataFrame. For example, you can use the `describe()` function to get values such as count, mean, standard deviation, minimum and maximum, as well as the various quartiles:

In [20]:
print(df.describe())

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.298621  -0.293948   0.511584  -0.341124
std     1.077697   0.679406   1.088207   0.764610
min    -1.950551  -1.737722  -0.676094  -2.040270
25%    -0.911431  -0.671574  -0.281318  -0.570455
50%    -0.422694  -0.158222   0.038312  -0.366735
75%     0.068605   0.283714   1.329047   0.059112
max     1.899104   0.410761   2.212451   0.741052


If you simply want to compute the mean in the DataFrame, you can use the `mean()` function, indicating the axis:

In [21]:
print(df.mean(0)) # 0 means compute the mean for each columns

A   -0.298621
B   -0.293948
C    0.511584
D   -0.341124
dtype: float64


If you want to get the mean for each row, set the axis to 1:

In [22]:
print(df.mean(1)) # 1 means compute the mean for each row

0   -0.068155
1   -0.106564
2    0.204529
3   -0.595185
4    0.184678
5   -0.404879
6    0.283049
7   -0.291350
8    0.157141
9   -0.418537
dtype: float64


<a id="dataframe-extracting"></a>
### Extracting from DataFrames

#### Selecting the First and Last Five Rows  
The `head()` function prints out the first five rows in the DataFrame:

In [23]:
print(df.head())

          A         B         C         D
0  0.118884  0.385206 -0.320386 -0.456324
1  0.734527 -1.737722 -0.164112  0.741052
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590
4 -0.567627 -0.572061  1.427365  0.451036


If you want more than five rows (or less than five), you can indicate the number of rows that you want in the `head()` function

In [24]:
print(df.head(8)) # prints out the first 8 rows

          A         B         C         D
0  0.118884  0.385206 -0.320386 -0.456324
1  0.734527 -1.737722 -0.164112  0.741052
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590
4 -0.567627 -0.572061  1.427365  0.451036
5 -0.572796 -0.820218 -0.156499 -0.070004
6  1.899104 -0.192962 -0.676094  0.102150
7 -1.950551  0.359557  1.034092 -0.608499


The `tail()` function prints the last five rows

In [25]:
print(df.tail())

          A         B         C         D
5 -0.572796 -0.820218 -0.156499 -0.070004
6  1.899104 -0.192962 -0.676094  0.102150
7 -1.950551  0.359557  1.034092 -0.608499
8 -0.082232 -0.704745  2.212451 -0.796912
9 -0.277762  0.410761  0.233124 -2.040270


Like the `head()` function, the `tail()` function allows you to specify the number of rows to print

In [26]:
print(df.tail(8)) # prints out the last 8 rows

          A         B         C         D
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590
4 -0.567627 -0.572061  1.427365  0.451036
5 -0.572796 -0.820218 -0.156499 -0.070004
6  1.899104 -0.192962 -0.676094  0.102150
7 -1.950551  0.359557  1.034092 -0.608499
8 -0.082232 -0.704745  2.212451 -0.796912
9 -0.277762  0.410761  0.233124 -2.040270


#### Selecting a Specific Column in a DataFrame 
To obtain one or more columns in a DataFrame, you can specify the column label as follows:

In [27]:
print(df['A'])
# same as
print('*************************************************')
print(df.A)

0    0.118884
1    0.734527
2   -1.024309
3   -1.263449
4   -0.567627
5   -0.572796
6    1.899104
7   -1.950551
8   -0.082232
9   -0.277762
Name: A, dtype: float64
*************************************************
0    0.118884
1    0.734527
2   -1.024309
3   -1.263449
4   -0.567627
5   -0.572796
6    1.899104
7   -1.950551
8   -0.082232
9   -0.277762
Name: A, dtype: float64


If you want to retrieve more than one column, pass in a list containing the column labels:

In [28]:
print(df[['A','B']])

          A         B
0  0.118884  0.385206
1  0.734527 -1.737722
2 -1.024309  0.056186
3 -1.263449 -0.123481
4 -0.567627 -0.572061
5 -0.572796 -0.820218
6  1.899104 -0.192962
7 -1.950551  0.359557
8 -0.082232 -0.704745
9 -0.277762  0.410761


#### Slicing Based on Row Number
First, let’s extract a range of rows in the DataFrame:

In [29]:
print(df[2:4])

          A         B         C         D
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590


You can also use the iloc indexer for extracting rows based on row number:

In [30]:
print(df.iloc[2:4])

          A         B         C         D
2 -1.024309  0.056186  2.075116 -0.288879
3 -1.263449 -0.123481 -0.549220 -0.444590


Note that if you wish to extract specific rows (and not a range of rows) using
row numbers, you need to use the iloc indexer like this:

In [31]:
print(df.iloc[[2,4]])

          A         B         C         D
2 -1.024309  0.056186  2.075116 -0.288879
4 -0.567627 -0.572061  1.427365  0.451036


Without using the iloc indexer, the following will not work:

In [68]:
# print(df[[2,4]]) # error; need to use the iloc indexer

The same applies when extracting a single row using a row number; you
need to use iloc:

In [33]:
print(df.iloc[2]) # prints out row number 2

A   -1.024309
B    0.056186
C    2.075116
D   -0.288879
Name: 2, dtype: float64


#### Slicing Based on Row and Column Numbers
If you wish to extract specific rows and columns in a DataFrame, you need to use the `iloc` indexer

In [34]:
print(df_2.iloc[2:4, 1:4])

                   B         C         D
2019-05-27  0.056186  2.075116 -0.288879
2019-05-28 -0.123481 -0.549220 -0.444590


You can also extract specific rows and columns

In [35]:
print(df_2.iloc[[2,4], [1,3]])

                   B         D
2019-05-27  0.056186 -0.288879
2019-05-29 -0.572061  0.451036


#### Slicing Based on Labels  
Besides extracting rows and columns using their row and column numbers, you can also extract them by label(value) 

In [36]:
print(df_2['20190501':'20190603'])

                   A         B         C         D
2019-05-25  0.118884  0.385206 -0.320386 -0.456324
2019-05-26  0.734527 -1.737722 -0.164112  0.741052
2019-05-27 -1.024309  0.056186  2.075116 -0.288879
2019-05-28 -1.263449 -0.123481 -0.549220 -0.444590
2019-05-29 -0.567627 -0.572061  1.427365  0.451036
2019-05-30 -0.572796 -0.820218 -0.156499 -0.070004
2019-05-31  1.899104 -0.192962 -0.676094  0.102150
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-06-02 -0.082232 -0.704745  2.212451 -0.796912
2019-06-03 -0.277762  0.410761  0.233124 -2.040270


You can also use the `loc` indexer

In [37]:
print(df_2.loc['20190601':'20190603'])

                   A         B         C         D
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-06-02 -0.082232 -0.704745  2.212451 -0.796912
2019-06-03 -0.277762  0.410761  0.233124 -2.040270


Using the `loc` indexer  is mandatory if you want to extract the columns using their _values_

In [38]:
print(df_2.loc['20190601':'20190603', 'A':'C'])

                   A         B         C
2019-06-01 -1.950551  0.359557  1.034092
2019-06-02 -0.082232 -0.704745  2.212451
2019-06-03 -0.277762  0.410761  0.233124


You can also extract specific columns

In [39]:
print(df_2.loc['20190601':'20190603', ['A','C']])

                   A         C
2019-06-01 -1.950551  1.034092
2019-06-02 -0.082232  2.212451
2019-06-03 -0.277762  0.233124


If you want to extract a specific row, use the `loc` indexer

In [40]:
print(df_2.loc['20190601'])

A   -1.950551
B    0.359557
C    1.034092
D   -0.608499
Name: 2019-06-01 00:00:00, dtype: float64


Oddly, if you want to extract specific rows with datetime as the index, you cannot simply pass the date value to the `loc` indexer

In [67]:
# print(df_2.loc[['20190601','20190603']]) # KeyError

First, you need to convert the date into a `datetime` format

In [42]:
from datetime import datetime

In [43]:
date1 = datetime(2019, 6, 1, 0, 0, 0)
date2 = datetime(2019, 6, 3, 0, 0, 0)
print(df_2.loc[[date1,date2]])

                   A         B         C         D
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-06-03 -0.277762  0.410761  0.233124 -2.040270


If you want a specific row and specific columns, you can extract them as follows

In [44]:
print(df_2.loc[date1, ['A','C']])

A   -1.950551
C    1.034092
Name: 2019-06-01 00:00:00, dtype: float64


<a id="single-cell-dataframe"></a>
### Selecting a Single Cell in a DataFrame

If you simply wish to access a single cell in a DataFrame, there is a function that does just that: `at()`

In [45]:
from datetime import datetime
d = datetime(2019, 6, 3, 0, 0, 0)
print(df_2.at[d, 'B'])

0.4107607305495597


<a id="selecting-based-cell-value"></a>
### Selecting Based on Cell Value

If you want to select a subset of the DataFrame based on certain values in the cells, you can use the Boolean Indexing method.

In [46]:
print(df_2[(df_2.A > 0) & (df_2.B > 0)])

                   A         B         C         D
2019-05-25  0.118884  0.385206 -0.320386 -0.456324


<a id="transforming-dataframes"></a>
### Transforming DataFrames

If you need reflect the DataFrame over its main diagonal(converting columns to rows and rows to columns), you can use the `transpose()` function:

In [48]:
print(df_2.transpose())

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.118884    0.734527   -1.024309   -1.263449   -0.567627   -0.572796   
B    0.385206   -1.737722    0.056186   -0.123481   -0.572061   -0.820218   
C   -0.320386   -0.164112    2.075116   -0.549220    1.427365   -0.156499   
D   -0.456324    0.741052   -0.288879   -0.444590    0.451036   -0.070004   

   2019-05-31  2019-06-01  2019-06-02  2019-06-03  
A    1.899104   -1.950551   -0.082232   -0.277762  
B   -0.192962    0.359557   -0.704745    0.410761  
C   -0.676094    1.034092    2.212451    0.233124  
D    0.102150   -0.608499   -0.796912   -2.040270  


Alternatively, you can just use the T property, which is an accessor to the `transpose()` function:

In [49]:
print(df_2.T)

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.118884    0.734527   -1.024309   -1.263449   -0.567627   -0.572796   
B    0.385206   -1.737722    0.056186   -0.123481   -0.572061   -0.820218   
C   -0.320386   -0.164112    2.075116   -0.549220    1.427365   -0.156499   
D   -0.456324    0.741052   -0.288879   -0.444590    0.451036   -0.070004   

   2019-05-31  2019-06-01  2019-06-02  2019-06-03  
A    1.899104   -1.950551   -0.082232   -0.277762  
B   -0.192962    0.359557   -0.704745    0.410761  
C   -0.676094    1.034092    2.212451    0.233124  
D    0.102150   -0.608499   -0.796912   -2.040270  


<a id="dataframes-series"></a>
### Checking to See If a Result is a DataFrame or Series

One the common problems that you will face with Pandas is knowing if the result that you have obtained is a Series or a DataFrame.

In [50]:
def checkSeriesOrDataframe(var):
    if isinstance(var, pd.DataFrame):
        return 'Dataframe'
    if isinstance(var, pd.Series):
        return 'Series'

In [51]:
checkSeriesOrDataframe(df_2)

'Dataframe'

In [52]:
checkSeriesOrDataframe(df_2.loc['20190601'])

'Series'

<a id="sorting-dataframe"></a>
### Sorting Data in a DataFrame

There are two ways that you can sort the data in a DataFrame:
1. Sort by labels(axis) using ther `sort_index()` function
2. Sort by value using the `sort_values()` function

#### Sorting by Index

To sort using the axis, you need to specify if you want to sort by index or column.

In [55]:
print(df_2.sort_index(axis=0, ascending=False)) # axis = 0 means sort by index

                   A         B         C         D
2019-06-03 -0.277762  0.410761  0.233124 -2.040270
2019-06-02 -0.082232 -0.704745  2.212451 -0.796912
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-05-31  1.899104 -0.192962 -0.676094  0.102150
2019-05-30 -0.572796 -0.820218 -0.156499 -0.070004
2019-05-29 -0.567627 -0.572061  1.427365  0.451036
2019-05-28 -1.263449 -0.123481 -0.549220 -0.444590
2019-05-27 -1.024309  0.056186  2.075116 -0.288879
2019-05-26  0.734527 -1.737722 -0.164112  0.741052
2019-05-25  0.118884  0.385206 -0.320386 -0.456324


__TIP__ If you want the original DataFrame to be sorted, use the `inplace` parameter and set it to `True`.

Setting the `axis` parameter to 1 indicates that you want to sort by column labels:

In [59]:
df_2.sort_index(axis=1, ascending=False) # axis = 1 means sort by column

D         C         B         A
2019-05-25 -0.456324 -0.320386  0.385206  0.118884
2019-05-26  0.741052 -0.164112 -1.737722  0.734527
2019-05-27 -0.288879  2.075116  0.056186 -1.024309
2019-05-28 -0.444590 -0.549220 -0.123481 -1.263449
2019-05-29  0.451036  1.427365 -0.572061 -0.567627
2019-05-30 -0.070004 -0.156499 -0.820218 -0.572796
2019-05-31  0.102150 -0.676094 -0.192962  1.899104
2019-06-01 -0.608499  1.034092  0.359557 -1.950551
2019-06-02 -0.796912  2.212451 -0.704745 -0.082232
2019-06-03 -2.040270  0.233124  0.410761 -0.277762

#### Sorting by Value

To sort by value, use `sort_values()` function. The following statement sorts the DataFrame based on the values in column "A".

In [58]:
df_2.sort_values('A', axis=0)

A         B         C         D
2019-06-01 -1.950551  0.359557  1.034092 -0.608499
2019-05-28 -1.263449 -0.123481 -0.549220 -0.444590
2019-05-27 -1.024309  0.056186  2.075116 -0.288879
2019-05-30 -0.572796 -0.820218 -0.156499 -0.070004
2019-05-29 -0.567627 -0.572061  1.427365  0.451036
2019-06-03 -0.277762  0.410761  0.233124 -2.040270
2019-06-02 -0.082232 -0.704745  2.212451 -0.796912
2019-05-25  0.118884  0.385206 -0.320386 -0.456324
2019-05-26  0.734527 -1.737722 -0.164112  0.741052
2019-05-31  1.899104 -0.192962 -0.676094  0.102150

To sort based on a particular index, set the axis parameter to 1:

In [60]:
df_2.sort_values('20190602', axis=1)

D         B         A         C
2019-05-25 -0.456324  0.385206  0.118884 -0.320386
2019-05-26  0.741052 -1.737722  0.734527 -0.164112
2019-05-27 -0.288879  0.056186 -1.024309  2.075116
2019-05-28 -0.444590 -0.123481 -1.263449 -0.549220
2019-05-29  0.451036 -0.572061 -0.567627  1.427365
2019-05-30 -0.070004 -0.820218 -0.572796 -0.156499
2019-05-31  0.102150 -0.192962  1.899104 -0.676094
2019-06-01 -0.608499  0.359557 -1.950551  1.034092
2019-06-02 -0.796912 -0.704745 -0.082232  2.212451
2019-06-03 -2.040270  0.410761 -0.277762  0.233124

<a id="functions-dataframe"></a>
### Applying Functions to a DataFrame

You can also apply functions to values in a DataFrame using `apply()` function.

In [62]:
import math
sq_root = lambda x: math.sqrt(x) if x > 0 else 0
sq = lambda x: x**2

It is important to note that objects passed to the `apply()` function are Series objects whose index is either the DataFrame´s index(axis=0) or the DataFrame's columns(axis=1)

In [63]:
df_2.B.apply(sq_root)

2019-05-25    0.620650
2019-05-26    0.000000
2019-05-27    0.237036
2019-05-28    0.000000
2019-05-29    0.000000
2019-05-30    0.000000
2019-05-31    0.000000
2019-06-01    0.599630
2019-06-02    0.000000
2019-06-03    0.640906
Freq: D, Name: B, dtype: float64

You can also apply the `sq()` function to `df_2.B`

In [64]:
df_2.B.apply(sq)

2019-05-25    0.148384
2019-05-26    3.019679
2019-05-27    0.003157
2019-05-28    0.015247
2019-05-29    0.327253
2019-05-30    0.672758
2019-05-31    0.037234
2019-06-01    0.129281
2019-06-02    0.496665
2019-06-03    0.168724
Freq: D, Name: B, dtype: float64

If you apply the `sq_root()` function to the DataFrame, you will get a `ValueError`

In [66]:
# df_2.apply(sq_root) # ValueError

This is because the object passed into the `apply()` function in this case is a DataFrame, not a Series. Interestingly, you can apply the `sq()` function to the DataFrame

In [69]:
df_2.apply(sq)

A         B         C         D
2019-05-25  0.014133  0.148384  0.102647  0.208231
2019-05-26  0.539530  3.019679  0.026933  0.549158
2019-05-27  1.049208  0.003157  4.306107  0.083451
2019-05-28  1.596304  0.015247  0.301643  0.197661
2019-05-29  0.322200  0.327253  2.037370  0.203434
2019-05-30  0.328096  0.672758  0.024492  0.004901
2019-05-31  3.606594  0.037234  0.457103  0.010435
2019-06-01  3.804649  0.129281  1.069346  0.370271
2019-06-02  0.006762  0.496665  4.894941  0.635068
2019-06-03  0.077152  0.168724  0.054347  4.162702

If you want to apply the `sq_root()` function to the entire DataFrame, you can iterate through the columns and apply the function to each column:

In [70]:
for column in df_2:
    df_2[column] = df_2[column].apply(sq_root)
print(df_2)

                   A         B         C         D
2019-05-25  0.344796  0.620650  0.000000  0.000000
2019-05-26  0.857046  0.000000  0.000000  0.860844
2019-05-27  0.000000  0.237036  1.440526  0.000000
2019-05-28  0.000000  0.000000  0.000000  0.000000
2019-05-29  0.000000  0.000000  1.194724  0.671592
2019-05-30  0.000000  0.000000  0.000000  0.000000
2019-05-31  1.378080  0.000000  0.000000  0.319610
2019-06-01  0.000000  0.599630  1.016903  0.000000
2019-06-02  0.000000  0.000000  1.487431  0.000000
2019-06-03  0.000000  0.640906  0.482829  0.000000


The `apply()` function can be applied on either axis: _index_ (0; apply function to each column) or _column_ (1; apply function to each row). For the two particular lambda functions that we have seen thus far, it does not matter which axis you apply it to, and the result would be the same. However, for some functions, the axis that you apply it to does matter. For example, the following statement uses the `sum()` function from NumPy and applies it to the rows of the DataFrame:

In [73]:
df_2.apply(np.sum, axis=0)

A    2.579921
B    2.098222
C    5.622413
D    1.852045
dtype: float64

If you set _axis_ to _1_, you will see the summation applied across each row:

In [74]:
df_2.apply(np.sum, axis=1)

2019-05-25    0.965445
2019-05-26    1.717889
2019-05-27    1.677562
2019-05-28    0.000000
2019-05-29    1.866316
2019-05-30    0.000000
2019-05-31    1.697689
2019-06-01    1.616533
2019-06-02    1.487431
2019-06-03    1.123735
Freq: D, dtype: float64

<a id="rows-columns"></a>
### Adding and Removing Rows and Columns in a DataFrame

In [75]:
import pandas as pd

In [77]:
data = {'name':['Janet', 'Nad', 'Timothy', 'June', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [6, 13, 14, 1, 7]}

In [78]:
df_3 = pd.DataFrame(data, index = ['Singapore', 'China', 'Japan', 'Sweden', 'Norway'])

In [79]:
df_3

name  year  reports
Singapore    Janet  2012        6
China          Nad  2012       13
Japan      Timothy  2013       14
Sweden        June  2014        1
Norway         Amy  2014        7

#### Adding a Column

Add a new column named "school" to the DataFrame:

In [80]:
import numpy as np

In [81]:
schools = np.array(["Cambridge","Oxford","Oxford","Cambridge","Oxford"])

In [82]:
df_3["school"] = schools

In [83]:
df_3

name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

#### Removing Rows

To remove one or more rows, use the `drop()` function.

In [84]:
df_3.drop(['China', 'Japan']) # drop rows based on value of index

name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford

__TIP__ Like the `sort_index()` function, by default the `drop()` function does not affect the original DataFrame. Use the `inplace` parameter if you want to modify the original DataFrame.

If you want to drop a row based on a particular column values, specify the column name and the condition like this:

In [86]:
df_3[df_3.name != 'Nad']

name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

You can also remove rows based on row number:

In [87]:
df_3.drop(df_3.index[1])

name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

If you want to drop multiple rows, specify the row numbers represented as a list:

In [88]:
df_3.drop(df_3.index[[1,2]]) # remove the second and third row

name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford

In [89]:
df_3.drop(df_3.index[-2]) # remove second last row

name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Norway         Amy  2014        7     Oxford

#### Removing Columns

The `drop()` function drops rows by default, but if you want to drop columns instead, set the _axis_ parameter to _1_ 

In [90]:
df_3.drop('reports', axis=1) # drop column

name  year     school
Singapore    Janet  2012  Cambridge
China          Nad  2012     Oxford
Japan      Timothy  2013     Oxford
Sweden        June  2014  Cambridge
Norway         Amy  2014     Oxford

If you want to drop by column number, specify the column number using the _columns_ indexer

In [91]:
df_3.drop(df_3.columns[1], axis=1) # drop using columns number

name  reports     school
Singapore    Janet        6  Cambridge
China          Nad       13     Oxford
Japan      Timothy       14     Oxford
Sweden        June        1  Cambridge
Norway         Amy        7     Oxford

You can also drop multiple columns

In [92]:
df_3.drop(df_3.columns[[1,3]], axis=1) # drop multiple columns

name  reports
Singapore    Janet        6
China          Nad       13
Japan      Timothy       14
Sweden        June        1
Norway         Amy        7

<a id="crosstab"></a>
### Generating a Crosstab 

In statistics, a _crosstab_ is used to aggregate and jointly display the distribution of two or more variables. It shows the relationships between these variables.

In [93]:
df_4 = pd.DataFrame(
 {
 "Gender": ['Male','Male','Female','Female','Female'],
 "Team" : [1,2,3,3,1]
 })

df_4

Gender  Team
0    Male     1
1    Male     2
2  Female     3
3  Female     3
4  Female     1

Using a crosstab, you would be able to summarize the data and generate a table to show the distribution of each gender for each team. To do that, you use the `crosstab()` function:

In [95]:
print('Displaying the distribution of genders in each team')
pd.crosstab(df_4.Gender, df_4.Team)

Displaying the distribution of genders in each team


Team    1  2  3
Gender         
Female  1  0  2
Male    1  1  0

If you want to see the distribution of each team for each gender, you simply
reverse the argument:

In [96]:
pd.crosstab(df_4.Team, df_4.Gender)

Gender  Female  Male
Team                
1            1     1
2            0     1
3            2     0